version: '2'

volumes:
    sync.ditt_api_root:
        external: true

services:
    web:
        image: visionappscz/apache-php:7.4
        links:
            - db
            - mail
        ports:
            - 80:80
        volumes:
            - sync.ditt_api_root:/www

    db:
        image: postgres:11
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass

    adminer:
        image: clue/adminer
        links:
            - db
        ports:
            - 81:80

    mail:
        image: mailhog/mailhog
        ports:
            - 82:8025
