App\Entity\BusinessTripWorkLog:
    attributes:
        id:
            groups:
                - business_trip_work_log_out_detail
                - business_trip_work_log_support_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        date:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - business_trip_work_log_in
        purpose:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - business_trip_work_log_in
        destination:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - business_trip_work_log_in
        transport:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - business_trip_work_log_in
        expectedDeparture:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - business_trip_work_log_in
        expectedArrival:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - business_trip_work_log_in
        timeApproved:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        timeRejected:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        rejectionMessage:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - business_trip_work_log_in
        support:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
        workMonth:
            groups:
                - business_trip_work_log_out_detail
                - special_approvals_out_list
