App\Entity\OvertimeWorkLogSupport:
    attributes:
        id:
            groups:
                - overtime_work_log_out_detail
                - overtime_work_log_support_out_detail
                - special_approvals_out_list

        dateTime:
            groups:
                - overtime_work_log_out_detail
                - overtime_work_log_support_out_detail
                - special_approvals_out_list

        supportedBy:
            groups:
                - overtime_work_log_out_detail
                - overtime_work_log_support_out_detail
                - special_approvals_out_list

        workLog:
            groups:
                - overtime_work_log_support_out_detail
                - overtime_work_log_support_in
