App\Entity\SpecialLeaveWorkLogSupport:
    attributes:
        id:
            groups:
                - special_leave_work_log_out_detail
                - special_leave_work_log_support_out_detail
                - special_approvals_out_list

        dateTime:
            groups:
                - special_leave_work_log_out_detail
                - special_leave_work_log_support_out_detail
                - special_approvals_out_list

        supportedBy:
            groups:
                - special_leave_work_log_out_detail
                - special_leave_work_log_support_out_detail
                - special_approvals_out_list

        workLog:
            groups:
                - special_leave_work_log_support_out_detail
                - special_leave_work_log_support_in
