App\Entity\TimeOffWorkLog:
    attributes:
        id:
            groups:
                - time_off_work_log_out_detail
                - time_off_work_log_support_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        date:
            groups:
                - time_off_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - time_off_work_log_in
        comment:
            groups:
                - time_off_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - time_off_work_log_in
        timeApproved:
            groups:
                - time_off_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        timeRejected:
            groups:
                - time_off_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        rejectionMessage:
            groups:
                - time_off_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - home_office_work_log_in
        support:
            groups:
                - time_off_work_log_out_detail
                - special_approvals_out_list
        workMonth:
            groups:
                - time_off_work_log_out_detail
                - special_approvals_out_list
