App\Entity\User:
    attributes:
        id:
            groups:
                - business_trip_work_log_support_out_detail
                - home_office_work_log_support_out_detail
                - hr_out_detail
                - overtime_work_log_support_out_detail
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - special_leave_work_log_support_out_detail
                - supervised_user_out_list
                - time_off_work_log_support_out_detail
                - vacation_work_log_support_out_detail
                - work_month_out_list
                - work_month_out_detail
        email:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - user_in
        employeeId:
            groups:
                - hr_out_detail
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - user_in
        firstName:
            groups:
                - hr_out_detail
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - work_month_out_detail
                - user_in
        lastName:
            groups:
                - hr_out_detail
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - work_month_out_detail
                - user_in
        plainPassword:
            groups:
                - user_in
        isActive:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - supervised_user_out_list
                - user_in
        roles:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - supervised_user_out_list
                - user_in
        supervisor:
            groups:
                - special_approvals_out_list
                - supervised_user_out_list
                - user_out_list
                - user_out_detail
                - user_in
        allSupervisors:
            groups:
                - special_approvals_out_list
                - user_out_list
                - user_out_detail
                - user_in
        vacations:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - supervised_user_out_list
                - work_month_out_detail
                - user_in
        workHours:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - supervised_user_out_list
                - user_in
        workMonths:
            groups:
                - supervised_user_out_list
        yearStats:
            groups:
                - user_out_detail
                - user_out_list
                - work_month_out_detail
        notifications:
            groups:
                - user_out_detail
                - user_in
        apiToken:
            groups:
                - user_out_detail
                - user_out_api_token_detail
        iCalToken:
            groups:
                - user_out_detail
                - user_out_ical_token_detail
