App\Entity\HomeOfficeWorkLog:
    type: entity

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        date:
            type: datetime_immutable
        comment:
            type: text
            nullable: true
        plannedEndHour:
            type: integer
        plannedEndMinute:
            type: integer
        plannedStartHour:
            type: integer
        plannedStartMinute:
            type: integer
        timeApproved:
            type: datetime_immutable
            nullable: true
        timeRejected:
            type: datetime_immutable
            nullable: true
        rejectionMessage:
            type: text
            nullable: true

    oneToMany:
        support:
            targetEntity: App\Entity\HomeOfficeWorkLogSupport
            mappedBy: workLog

    manyToOne:
        workMonth:
            targetEntity: App\Entity\WorkMonth
            inversedBy: homeOfficeWorkLogs
            joinColumn:
                name: work_month_id
                referencedColumnName: id
                nullable: false
