App\Entity\UserYearStats:
    type: entity
    table: app_user_year_stats

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    indexes:
        year_user_idx:
            columns: [year, user_id]
            type: unique
        year_idx:
            columns: [year]

    fields:
        requiredHours:
            type: integer
        workedHours:
            type: integer
        vacationDaysUsed:
            type: integer

    manyToOne:
        user:
            targetEntity: App\Entity\User
            inversedBy: yearStats
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
        year:
            targetEntity: App\Entity\SupportedYear
            joinColumn:
                name: year
                referencedColumnName: year
                nullable: false
                onDelete: cascade
