App\Entity\VacationWorkLog:
    type: entity

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        date:
            type: datetime_immutable
        timeApproved:
            type: datetime_immutable
            nullable: true
        timeRejected:
            type: datetime_immutable
            nullable: true
        rejectionMessage:
            type: text
            nullable: true

    oneToMany:
        support:
            targetEntity: App\Entity\VacationWorkLogSupport
            mappedBy: workLog

    manyToOne:
        workMonth:
            targetEntity: App\Entity\WorkMonth
            inversedBy: vacationWorkLogs
            joinColumn:
                name: work_month_id
                referencedColumnName: id
                nullable: false
