App\Entity\SpecialLeaveWorkLogSupport:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - special_leave_work_log_support_out_detail
            denormalization_context:
                groups:
                    - special_leave_work_log_support_in
        bulkCreate:
            method: POST
            route_name: api_special_leave_work_log_support_bulk_create
            swagger_context:
                summary: Creates multiple SpecialLeaveWorkLogSupport resource.
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - special_leave_work_log_support_out_detail
