App\Entity\VacationWorkLogSupport:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - vacation_work_log_support_out_detail
            denormalization_context:
                groups:
                    - vacation_work_log_support_in
        bulkCreate:
            method: POST
            route_name: api_vacation_work_log_support_bulk_create
            swagger_context:
                summary: Creates multiple VacationWorkLogSupport resource.
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - vacation_work_log_support_out_detail
